### ISSUE TITLE
Wrong Role assignment for ""

### ISSUE THREAD

**Issue by zurk** [bblfsh/python-driver#107]
If you extract UAST for 
```python
""""
``` 
You have next tree:
```
#  Token  Internal Role  Roles Tree                 
                                                    
   ||     Module         FILE                       
1  ||     Expr           ┣ EXPRESSION               
1  ||     Str            ┗ ┗ BYTE, TUPLE, EXPRESSION
```
What I expect to see is:
```
#  Token  Internal Role  Roles Tree                 
                                                    
   ||     Module         FILE                       
1  ||     Expr           ┣ EXPRESSION               
1  ||     Str            ┗ ┗ ~BYTE~, ~TUPLE~, EXPRESSION, +STRING+, +VALUE+ 
```
Legend:
```
+ROLE+ -- add Role
~ROLE~ -- remove Role
?ROLE? -- maybe add/remove Role
```

Gist to generate UAST Roles visualization: https://gist.github.com/zurk/d314d67d9aac8843d3776c82cd738b40

**Comment by juanjux** [comment]
Was because of the desync between the SDK numeric roles. With the latest versions (that should be incorporated in the python-driver 1.0.3 docker image) I get:

Literal, String, Expression.

Value in this case is not a literal value (that's what literal is for) but the value part in a key-value pair.
