### ISSUE TITLE
The same line + column for multiple call expressions

### ISSUE THREAD

**Issue by Gnouc** [bblfsh/python-driver#174]
With a `test.py` file:

```
res.offset(offset).limit(limit).all()
```

Parsing with bblfsh server:

```
import bblfsh

client = bblfsh.BblfshClient("0.0.0.0:9432")
uast = client.parse("./test.py").uast
it = bblfsh.iterator(uast, bblfsh.TreeOrder.PRE_ORDER)
for node in it:
    if node.internal_type == 'Call':
        print(node.start_position)
```

Output:

```
line: 1
col: 1

line: 1
col: 1

line: 1
col: 1
```

**Comment by juanjux** [comment]
Sorry for the late reply, I was on holidays. Will take a look at this soon, thanks for reporting!

**Comment by juanjux** [comment]
Ok, here is the problem:

Some Python nodes doesn't add the correct positions, `Call` being one of them. We fix them with a light tokenizing pass by finding the token positions and updating the node ones, but in this case the node doesn't have a token since it's a "Containing" or virtual one, so you need to get the position of the `Call` token which you can get with:

```python
nodes = bblfsh.filter(uast, "//*[@roleCall and @roleIdentifier]")
```
