### ISSUE TITLE
A child process hangs if I import bblfsh

### ISSUE THREAD

**Issue by zurk** [bblfsh/python-driver#55]
If you run this code
```python
import os
import sys
import time

import bblfsh

def func(n):
    print('Sleep during {} sec...'.format(n))
    time.sleep(n)
    return n

if __name__ == '__main__':
    for n in range(1, 3):
        pid = os.fork()
        if pid == 0:
            # if you do import bblfsh in this place everythink will be fine
            res = func(n)
            print('Sleep in is Done!')
            sys.exit(0)
        else:
            print('os.waitpid is waiting for {}...'.format(pid))
            _, status = os.waitpid(pid, 0)
            print('os.waitpid is fine!')
    print('ok, terminate.')
```
You will see, that first child process hangs during `sys.exit(0)`.
If you comment `import bblfsh` everything will be fine. 
Also, you can replace `import bblfsh` with 
```python 
from bblfsh.github.com.bblfsh.sdk.protocol.generated_pb2 import ParseResponse
```
and have the same effect. And here is the main point. The problem is not exactly in bblfsh, but in `grpc`.

Seems that `ParseResponse` should be imported in child process because grpc starts threads during import and if you call fork after that, a child process will be hang during exit.

And here https://github.com/grpc/grpc/issues/7951#issuecomment-244137078 you can find that fork is not supported. 

So, the reason I write it here is just FYI, I think it is important to know.

And may be it is not a big deal to move `ParseRequest` and `ProtocolServiceStub` imports in `/bblfsh/client.py` to the place, where they are directly called. It can help to avoid this kind of problems. Or find more elegant way. What do you think?

P.S.: test it on MacOS and Ubuntu.

**Comment by juanjux** [comment]
I've been playing with subprocess, multiprocessing and other modules to try to workaround the issue but as expected it didn't work.

An option is to use Python threading if you're not executing subprocessing (because of the global lock Python threads never really run in parallel but since most of this would be waiting on the network or the parser the concurrency would speed things up) or as you said importing bblfsh after the fork.

Anyway I made a PR moving the imports as you suggested so if you don't mind as soon as is reviewed and merged I'll close this.

Thanks for discovering and reporting this.

https://github.com/bblfsh/client-python/pull/20

**Comment by juanjux** [comment]
There are external modules that implement multiprocessing using separate processes communicating via unix or TCP sockets, that maybe could also help you depending on your use case, but I'm unsure if they really use fork internally:

https://pythonhosted.org/joblib/index.html
http://dask.pydata.org/en/latest/

**Comment by juanjux** [comment]
PR merged.

**Comment by zurk** [comment]
Thank you, @juanjux. I will take a look at this libraries.
