### ISSUE TITLE
Incorrect positions for nodes: nodes have the same position (line continuation?)

### ISSUE THREAD

**Issue by EgorBu** [bblfsh/python-driver#72]
Hi,
I made some experiments and found bug - SIMPLE_IDENTIFIER nodes have the same positions.

Reproducible example:
```
a += b.c["Some val"] \
    .d
```

And uast_playground gives us:
```
# New token 'b' at position (1, 6) has the same position as token 'd' at the same position. Skip new token.
a += b.c["Some val"] \
# Something wrong with token 'd' at pos (1, 6) - it's not equal to 'b' at this position in code
    .d
```

It looks like that it happens because of line continuation because in case of code:
```
a += b.c["Some val"].d
```
everything works well.

BTW: it looks like that `d` is higher in UAST than `b` - is it correct? Because it appears earlier during traversing of UAST

Screenshot: 
![selection_001](https://user-images.githubusercontent.com/2606702/29319898-e013814a-81d5-11e7-9c95-62d09fb5e206.png)

**Comment by juanjux** [comment]
Yes, the qualified identifiers are given that way in the native AST, nested, so that is a #wontfix. About the line break, I must confess that I didn't try with them but could also be that the native tokenizer that we use to add positions to some nodes missing them (like in this case) consider line breaks as the same logical lines. 

If you add a line break are the positions of all elements below if shited by -1 line number or not? I mean, what is the line number of x in:

a = b.\
  c
x = 3

If it's 2, then the tokenizer use logic lines and nothing reasonable can be done in this case. If its 3 then maybe this part can be fixed.

**Comment by juanjux** [comment]
Sorry, forgot to scape, the test code is:

```python
a = b.\
  c
x = 3
```

**Comment by EgorBu** [comment]
Yes, `x` has correct positions
![selection_005](https://user-images.githubusercontent.com/2606702/29321483-d47bd3aa-81da-11e7-8787-4580edc69c97.png)
```
token: "x"
      start_position {
        offset: 31
        line: 4
        col: 1
      }
      end_position {
        offset: 31
        line: 4
        col: 1
      }
      roles: ASSIGNMENT_VARIABLE
      roles: SIMPLE_IDENTIFIER
      roles: EXPRESSION

```

**Comment by abeaumont** [comment]
Depends on https://github.com/bblfsh/sdk/issues/163

**Comment by juanjux** [comment]
I've checked that the native AST considers all the items after a line continuation character (`\') as being in the same line but items in the new lines after this have their line numbers right (so a node in line 3 would be in line 3 in the UAST).

Since currently we're not adding workarounds for missing/questionable positions in the native AST I've to close this.
